apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: custom-config
  namespace: kg-llm
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true
