apiVersion: apps/v1
kind: Deployment
metadata:
  name: kg-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kg-llm
  template:
    metadata:
      labels:
        app: kg-llm
    spec:
      containers:
      - name: kg-llm-container
        image: ghcr.io/sdsc-ordes/kg-llm-interface:latest 
        env:
        - name: CHROMA_HOST
          value: "servicename.servicenamespace.svc.cluster.local"
        - name: CHROMA_PORT
          value: "0"
        ports:
        - containerPort: 80
