apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
- name: kg-llm-config
  namespace: kg-llm
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: kg-llm-config
    fieldPath: data.GRAPHDB_SERVICE_NAME
  targets:
  - select:
      kind: Deployment
      name: kg-llm
    fieldPaths:
    - spec.template.spec.containers.[name=kg-llm-container].env.[name=GRAPHDB_HOST].value
    - spec.template.spec.initContainers.[name=graphdb-upload-container].env.[name=GRAPHDB_HOST].value
- source:
    kind: ConfigMap
    name: kg-llm-config
    fieldPath: data.GRAPHDB_PORT
  targets:
  - select:
      kind: Deployment
      name: kg-llm
    fieldPaths:
    - spec.template.spec.containers.[name=kg-llm-container].env.[name=GRAPHDB_PORT].value
    - spec.template.spec.initContainers.[name=graphdb-upload-container].env.[name=GRAPHDB_PORT].value
- source:
    kind: ConfigMap
    name: kg-llm-config
    fieldPath: data.CHROMA_SERVICE_NAME
  targets:
  - select:
      kind: Deployment
      name: kg-llm
    fieldPaths:
    - spec.template.spec.containers.[name=kg-llm-container].env.[name=CHROMA_HOST].value
    - spec.template.spec.initContainers.[name=chroma-upload-container].env.[name=CHROMA_HOST].value
- source:
    kind: ConfigMap
    name: kg-llm-config
    fieldPath: data.CHROMA_PORT
  targets:
  - select:
      kind: Deployment
      name: kg-llm
    fieldPaths:
    - spec.template.spec.containers.[name=kg-llm-container].env.[name=CHROMA_PORT].value
    - spec.template.spec.initContainers.[name=chroma-upload-container].env.[name=CHROMA_PORT].value
