apiVersion: batch/v1
kind: Job
metadata:
  name: data-retriever
spec:
  template:
    spec:
      containers:
      - name: data-retriever-container
        image: daniilzhyrov/kg-llm:latest
        env:
        - name: CHROMA_HOST
          value: "servicename.servicenamespace.svc.cluster.local"
        - name: CHROMA_PORT
          value: "0"
        - name: SPARQL_HOST
          value: "servicename.servicenamespace.svc.cluster.local"
        - name: SPARQL_PORT
          value: "0"
        command: ["/bin/bash",  "/app/kubernetes/overlays/data-retriever/entrypoint.sh"]
      restartPolicy: Never
  parallelism: 1
