apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuseki
  template:
    metadata:
      labels:
        app: fuseki
    spec:
      containers:
        image: renku/renku-jena