apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma-server
  namespace: kg-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      restartPolicy: Always
      containers:
      - name: kg-llm-chroma
        image: ghcr.io/chroma-core/chroma:0.4.24
        command:
        - uvicorn
        args: ["chromadb.app:app", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", $(CHROMA_PORT), "--log-config", "chromadb/log_config.yml"]
        env:
        - name: IS_PERSISTENT
          value: "true"
        - name: CHROMA_PORT
          value: chroma_port_placeholder
        ports:
        - containerPort: 0
          name: chroma-port
        volumeMounts:
        - name: chroma-index-data
          mountPath: /index_data
      volumes:
      - name: chroma-index-data
        persistentVolumeClaim:
          claimName: chroma-index-data
