apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: kg-llm
spec:
  type: ClusterIP
  selector:
    app: chroma
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
