apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: graphdb-config
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: graphdb-config
    fieldpath: data.GRAPHDB_PORT
  targets:
  - select:
      kind: Deployment
      name: graphdb
    fieldPaths:
    - spec.template.spec.containers.[name=graphdb].ports.[name=graphdb].containerPort
  - select:
        kind: Service
        name: graphdb-service
    fieldPaths:
    - spec.ports.[name=http].targetPort
    - spec.ports.[name=http].port
