apiVersion: v1
kind: Service
metadata:
  name: graphdb-service
  namespace: kg-llm
spec:
  type: ClusterIP
  selector:
    app: graphdb
  ports:
  - protocol: TCP
    port: 0
    targetPort: 0
    name: http
