
# set maximum input size
max_input_size: 2048
# set number of output tokens
num_output: 256
# set maximum chunk overlap
max_chunk_overlap: 20

template: |-
  We have provided the contextual facts below in the form of
  <subject> <predicate> <object> triples.

  -----------------
  {context_str}
  -----------------

  Please answer the question using only the context and no
  prior knowledge. If the context is insufficient to answer
  the question, simply answer the words 'Not found'.

  Question: {query_str}
